WITH CTE1 AS (
    SELECT USER1_ID, USER2_ID FROM FRIENDSHIP 
    UNION 
    SELECT USER2_ID AS USER1_ID, USER1_ID AS USER2_ID FROM FRIENDSHIP 
), CTE2 AS (
    SELECT *,
        ROW_NUMBER() OVER(PARTITION BY C1.USER1_ID, L1.PAGE_ID) RN,
        COUNT(*) OVER(PARTITION BY C1.USER1_ID, L1.PAGE_ID) CNT 
    FROM CTE1 AS C1
        INNER JOIN LIKES AS L1 
            ON C1.USER2_ID = L1.USER_ID
    WHERE NOT EXISTS (
        SELECT *
        FROM LIKES AS L2
        WHERE L2.USER_ID = C1.USER1_ID
        AND L2.PAGE_ID = L1.PAGE_ID
    )
)
SELECT 
    USER1_ID AS user_id,
    PAGE_ID AS page_id,
    CNT AS friends_likes 
FROM CTE2
WHERE RN = 1